#!/bin/bash

echo "----------Install Scipt----------"

mkdir install-script-files

cd install-script-files

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/release/install.sh" && chmod +x install.sh &&

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/release/varsetup.sh" && chmod +x varsetup.sh &&

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/release/pkg-install.sh" && chmod +x pkg-install.sh &&

./varsetup.sh &&

./install.sh
