#!/bin/bash

echo "----------Install Scipt----------"

mkdir install-script-files

cd install-script-files

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/master/install.sh" && chmod +x install.sh

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/master/varsetup" && chmod +x varsetup.sh

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/master/install.sh" && chmod +x pkg-setup.sh

./varsetup.sh

./install.sh
