#!/bin/bash

echo "----------Install Scipt----------"

mkdir install-script-files

cd install-script-files

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/master/install.sh" && chmod +x install.sh &&

wget -q "https://raw.githubusercontent.com/cezarmathe/install-script/master/varsetup.sh" && chmod +x varsetup.sh &&

./varsetup.sh &&

# ./install.sh
